### PR TITLE
New Brand visuals

### PR DESCRIPTION
**Pull request by AdrianoCahete**
For now is just the logo but it's already the finished one.
I need to finish the Brand Guide with all the specs (and I may write a medium post about this work, can I?)

Moved the old logo to a pma_legacy folder instead of delete because of history (and I don't know if you want to do something with that before the deletion, even with git as history-version control)

**Logo Default**
phpMyAdmin-Logo-Default

**Logo as a Symbol**
phpMyAdmin-Logo-Symbol

Typography is [Montserrat ](https://fonts.google.com/specimen/Montserrat#about) (is a SIL Open Font License).

### CODE REVIEW

**Comment by ibennetch** [comment]
I think this is beautiful work and don't have much to say about the logo itself.

I wonder what the motivation is for using a `.brand/` folder, is there any reason to not use a folder name like `logo/`? Especially since the . will hide it in many file browsers, this seems strange to me, but maybe you have a reason that I don't see.

Personally I think we should keep the old logos; I like putting them in a legacy or archive folder rather than deleting them.

**Comment by williamdes** [comment]
> and I may write a medium post about this work, can I?

I agree, feel free to send us a link ;p

**Comment by AdrianoCahete** [comment]
> I wonder what the motivation is for using a .brand/ folder, is there any reason to not use a folder name like logo/? Especially since the . will hide it in many file browsers, this seems strange to me, but maybe you have a reason that I don't see.

Nothing special, I just follow that idea because of habit (most of the time I have a `brand` or `asset` folder that needs to be part of the project, but not be deployed, so I use the dot notation).

Folder renamed.

**Comment by mauriciofauth** [comment]
Great work! :100: 

> I may write a medium post about this work, can I?

It's fine by me.

**Review by MauricioFauth — APPROVED** [review]

**Comment by AdrianoCahete** [comment]
I may deliver the Brand Guide in another PR, ok? With that, we can merge this PR with the new brand and proceed to merge the PR for the new Design on the webiste.

**Review by williamdes — APPROVED** [review]

**Comment by AdrianoCahete** [comment]
@mauriciofauth @williamdes Is something missing for the merge?

**Comment by ibennetch** [comment]
That's probably on me more than the other two holding up the merge. And no, there's nothing wrong, just that we (I) get easily distracted especially when working with repositories I don't look at all the time such as this one. I'm on mobile now, but thanks for the reminder.

**Comment by williamdes** [comment]
I can merge if @ibennetch approves, I do not see anyone else missing ;)

**Comment by AdrianoCahete** [comment]
The article about the brand refresh is here: https://adrianocahete.medium.com/design-for-opensource-phpmyadmin-8b0bd8b800d3

I'll post the article about the Website redesign soon!

**Pull request merged**
